// <!-- build:scripts -->
// <!-- utilities. -->



// @codekit-append "./routing.js"
// @codekit-append "./services/setup.js"
// @codekit-append "./services/app-settings.js"
// @codekit-append "./services/utils.js"
// @codekit-append "./services/customer.js"
// @codekit-append "./services/inspection.js"
// @codekit-append "./services/machine.js"
// @codekit-append "./services/user.js"
// @codekit-append "./services/dealer.js"
// @codekit-append "./services/password.js"
// @codekit-append "./services/auth.js"
// @codekit-append "./services/scoreboard.js"
// @codekit-append "./services/template.js"
// @codekit-append "./controllers/password-set-reset.js"
// @codekit-append "./controllers/update.js"
// @codekit-append "./modustri-dir.js"
// @codekit-append "./controllers/navigation.js"
// @codekit-append "./controllers/dashboard.js"
// @codekit-append "./controllers/customers-list.js"
// @codekit-append "./controllers/customer.js"
// @codekit-append "./controllers/customer-add.js"
// @codekit-append "./controllers/inspection.js"
// @codekit-append "./controllers/inspection-permalink.js"
// @codekit-append "./controllers/inspections-list.js"
// @codekit-append "./controllers/machines-list.js"
// @codekit-append "./controllers/machine-add.js"
// @codekit-append "./controllers/machine.js"
// @codekit-append "./controllers/user.js"
// @codekit-append "./controllers/settings.js"
// @codekit-append "./controllers/login.js"
// @codekit-append "./controllers/password.js"
// @codekit-append "./controllers/reports.js"
// @codekit-append "./controllers/longranges.js"
// @codekit-append "./controllers/drilldowns.js"
